### ISSUE TITLE
Nested structure?

### ISSUE THREAD

**Issue by ghost** [tomjohnson1492/documentation-theme-jekyll#119] opened 2018-01-30 15:59 UTC
Hi,

I want the generated htmls to be put in specific dirs under `_site`.  It works well with `permalink: dir/page.html`

However, this break all links to js and css files since they are being looked for in the same dir, not in the root where they are.

Anything I'm doing wrong?

**Comment by erinkcochran87** [comment] 2018-01-31 18:23
@eivantsov Are you adding `{{ site.baseurl }}` to your file paths? I ran into this issue awhile back and this solved it. Without seeing your code, though, I'm not sure if that's really what's happening.

Explicit location:
```
{{ site.baseurl }}/some-file.css 
```

Versus relative:

```
/some-file.css
```

[Blog post](https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/) that explains this.

**Comment by ghost** [comment] 2018-02-02 06:51
For me subdirs are different for different pages.

**Comment by ghost** [comment] 2018-10-23 22:53
`{{ site.baseurl }}` expands to the base directory for the site. You then append the path through the subdirs to the files in question. I have these in my equivalent to head.html:
```
    <link rel="stylesheet" type="text/css" href="{{site.baseurl}}/css/main.css" />
    <link rel="shortcut icon" href="{{site.baseurl}}/favicon.ico" />
    <script src="{{site.baseurl}}/js/jquery.navgoco.min.js"></script>
    <script src="{{site.baseurl}}/js/toc.js"></script>
```
All those paths expand to the right thing, no matter where they are in my source subdirectories.

**Comment by tomjoht** [comment] 2019-05-26 06:10
Closing -- as EXPErdefavero explained, I think the issue is specific to the user not configuring site.baseurl correctly in the config file.

**Closed as completed by tomjoht** 2019-05-26 06:10 UTC
