### ISSUE TITLE
news link disables

### ISSUE THREAD

**Issue by RoySRose** [tomjohnson1492/documentation-theme-jekyll#131] opened 2018-05-18 08:54 UTC
If I try to input a link inside a news. It is disabled.

For example. I've created 2018-05-11-news_test.md file under _post folder.
and if I put the content as below.
````
Visit [here](https://test).
````
Looks like converting to html file is correct as below.
````
<p>Visit <a href="https://test">here</a> .</p>
````
But.. still can't click *here* if I try to access through the homepage.

**Comment by instancezero** [comment] 2018-07-19 23:18
similar issue. Updated a blog post, got these errors:
      Regenerating: 1 file(s) changed at 2018-07-19 18:36:14
                    _posts/2018-07-19-hello_world.md
                    ...done in 2.891634232 seconds.

[2018-07-19 18:36:22] ERROR `/news/css/syntax.css' not found.
[2018-07-19 18:36:22] ERROR `/news/js/jquery.navgoco.min.js' not found.
[2018-07-19 18:36:22] ERROR `/news/css/modern-business.css' not found.
[2018-07-19 18:36:22] ERROR `/news/css/customstyles.css' not found.
[2018-07-19 18:36:22] ERROR `/news/css/theme-blue.css' not found.
[2018-07-19 18:36:22] ERROR `/news/css/boxshadowproperties.css' not found.
[2018-07-19 18:36:22] ERROR `/news/js/toc.js' not found.
[2018-07-19 18:36:22] ERROR `/news/js/jekyll-search.js' not found.
[2018-07-19 18:36:22] ERROR `/news/js/customscripts.js' not found.
[2018-07-19 18:36:22] ERROR `/news/images/company_logo.png' not found.
[2018-07-19 18:36:22] ERROR `/news/js/jquery.navgoco.min.js' not found.
[2018-07-19 18:36:22] ERROR `/news/js/toc.js' not found.
[2018-07-19 18:36:22] ERROR `/news/js/customscripts.js' not found.
[2018-07-19 18:36:22] ERROR `/news/js/jekyll-search.js' not found.
[2018-07-19 18:36:22] ERROR `/news/images/company_logo.png' not found.
[2018-07-19 18:36:22] ERROR `/news/images/favicon.ico' not found.
There's no base link, so the browser is looking for resources under news/

**Comment by tomjoht** [comment] 2019-05-26 06:28
I added links in news.html and in a blog post, and in both cases did not experience any issues. If you still have trouble, let me know. Otherwise, I'll close this as I cannot reproduce it.

**Closed as completed by tomjoht** 2019-05-26 06:28 UTC

**Comment by ghost** [comment] 2019-05-28 21:30
The problem @instance reports might be a baseurl configuration issue.

Try looking at using the {{ baseurl }} and {{ _link}} directives from Liquid together to specify the complete paths to things. (Look at the comments on this other issue: https://github.com/tomjoht/documentation-theme-jekyll/issues/119#issuecomment-495972671)
